1. Pandas stands for either Panel Data or Python Data Analysis. 
2. The two collections used in Pandas are Series and DataFrames. 
3. Pandas can do a series of things for us, such as: 
- Data visualization
- Data cleansing
- Data filling
- Loading data
4. To permanantly sort a DataFrame, one would use `inplace = True` within the `df.sort()` method. 
5. A CSV is a file that contains data. CSV's only contain plain text and are values are seperated by commas. Therefore, it's easy for Pandas to read.
6. When cleaning data we do not like `Null` values. 

In [2]:
import numpy as np
import pandas as pd

# Question 7

array_q7 = np.arange(12).reshape((2,3,2))
print(array_q7)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
# Question 8

new_array = np.linspace(0,20,num= 6)
print(new_array)

# Question 9 

import copy
copy_new_array = copy.deepcopy(new_array)
print(copy_new_array)

[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


In [22]:
# Question 10

array1 = ([[25,16]])
array2 = ([[11,2], [13,4]])
array3 = ([[7,81], [5,6], [11, 12]])

newArray = np.concatenate((array1, array2, array3))
print(newArray)

# Question 11

sortedArray = np.sort(newArray)
print(sortedArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [113]:
# Question 12

variable1 = array1
variable2 = array2
variable3 = array3[:2]
variable4 = array3[2:]

print("1st group...", variable1)
print("2nd gorup...", variable2)
print("3rd group...", variable3)
print("Last bunch...", variable4)

1st group... [[25, 16]]
2nd gorup... [[11, 2], [13, 4]]
3rd group... [[7, 81], [5, 6]]
Last bunch... [[11, 12]]


In [5]:
# Question 13

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

# combine arrays
comboArray = np.concatenate((one, two, three))

# sort array
comboArray = np.sort(comboArray, axis= -1)

# Question 14

print("\nSorted and concatenated array:\n",comboArray, "\n")
print("sec1: ",comboArray[1:2])
print("sec2: ",comboArray[2:])
print("sec3: ",comboArray[3:14])
print("sec4: ",comboArray[-6:])
print("sec5: ",comboArray[-27:15])
print("sec6: ",comboArray[20::2])
print("sec7: ",comboArray[27::-5])



Sorted and concatenated array:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27] 

sec1:  [1]
sec2:  [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3:  [ 3  4  5  6  7 10 11 12 13 14 15]
sec4:  [22 23 24 25 26 27]
sec5:  [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
sec6:  [24 26]
sec7:  [27 22 15 10  3]


In [ ]:
# 13. Concatenating three arrays together then sorting them

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7]) 

# combine arrays
comboArray = np.concatenate((one, two, three))

# sorting array
sortedcomboArray = np.sort(comboArray)
print(sortedcomboArray)

# 14. Slicing comboArray
sec1 = sortedcomboArray[2:3]
print(sec1)
sec2 = sortedcomboArray[3:24]
print(sec2)
sec3 = sortedcomboArray[4:15]
print(sec3)
sec4 = sortedcomboArray[-6:]
print(sec4)
sec5 = sortedcomboArray[:-10]
print(sec5)
sec6 = sortedcomboArray[16::2]
print(sec6)
sec7 = sortedcomboArray[::-5]
print(sec7)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[2]
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [86]:
# Question 15

ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name= 'Ingredients')
quantity = pd.Series([4,1,2,1], name= 'Quantity')
units = pd.Series(["cups", "cup", "large", "can"], name= 'Units')

df0 = pd.concat([ingredients, quantity, units], axis=1)
df0

Ingredients  Quantity  Units
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [13]:
# Question 16

studentData= {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

df1 = pd.DataFrame(studentData)
print(df1)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [28]:
# Question 17

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
df1['Deserts'] = deserts
df1

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

In [14]:
# Question 18

df1.sort_values(by= ['Name', 'address'], inplace = True, ascending = True)
df1

Name  Height Qualification  address  Age        Pets           sport
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball

In [87]:
# Quetion 19

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
fileName = "cows_and_goats.csv"
df.to_csv(fileName, index=False)
print(fileName)

cows_and_goats.csv


In [100]:
# Question 20

dfv = pd.DataFrame([["Broccoli", "Green"], ["Carrot", "Orange"], ["Onion", "Red"]],
                           columns= ['Vegetable', 'Color'])

dfv.to_csv('data_on_vegetables.csv')
print(dfv)

dfv = pd.read_csv(r"C:\Users\Bcbra\Code\SavvyCoders\Homework\data_on_vegetables.csv")
dfv.loc[2, "Color"] = "White"
updated_veggie = "update_data_on_vegetable.csv"
print(dfv.to_string(index= False))


  Vegetable   Color
0  Broccoli   Green
1    Carrot  Orange
2     Onion     Red
 Unnamed: 0 Vegetable  Color
          0  Broccoli  Green
          1    Carrot Orange
          2     Onion  White
